### ISSUE TITLE
In Eclipse, start the write server, followed by the read server, and finally the acxiomread server. Step#32 in accelerator_acxiom_dataretrieval.md

### ISSUE THREAD

**Issue by lawndale5** [IBM-i2/Data-Acquisition-Accelerators#4]
In the order directions specify write and read servers start up but acxiomread server failing on launch log below:

Launching acxiomread (WebSphere Application Server 8.5.5.5/wlp-1.0.8.cl50520150305-2202) on IBM J9 VM, version pwa6470_27sr2fp10ifx-20150313_01 (SR2 FP10+IV70681) (en_US)
[AUDIT   ] CWWKE0001I: The server acxiomread has been launched.
[AUDIT   ] CWWKG0028A: Processing included configuration resource: C:\IBM\WebSphere\Liberty\usr\servers\acxiomread\server.datasources.xml
[AUDIT   ] CWWKG0028A: Processing included configuration resource: C:\IBM\WebSphere\Liberty\usr\shared\config\server.security.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications. 
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://iap01.i2enablement.softlayer.com:20046/b962ca18-5bd5-46a5-a903-fd8d4ea94ebc/
[ERROR   ] SRVE0283E: Exception caught while initializing context: com.google.inject.CreationException: Guice creation errors:

1) An exception was caught and reported. Message: Parameter named 'IExternalDataDocumentSource' is not set.  Parameters were loaded from [DataSourceDaod.properties, ApolloServerSettingsCommon.properties, SearchLocalization.properties, ApolloServerSettingsCommonSearch.properties, ApolloServerSettingsSearch.properties, SearchIndexLocation.properties, ApolloServerSettingsOtherReadSide.properties, ApolloServerSettingsMandatory.properties, ApolloServerSettingsDaod.properties, ApolloServerSettingsDaodMandatory.properties], which provided {MaxNumberOfTrigramsToRetrieveForFullTextSearch=100, TransactionTimeoutInSeconds=300, ServerMaxItemVersionResultCount=1000, ReconnectIntervalInSeconds=30, DataSourceId=b962ca18-5bd5-46a5-a903-fd8d4ea94ebc, TextIndexSchedulerQueueLength=1000, ChartingSchemesResource=counter-fraud-schema-charting-schemes.xml, MaxNumberOfSynonymsToRetrieveForPropertySearch=100, ExternalDataSourceFilteredSearchMode=0, TermIndex=C:/iap-data/daod1/alternatives, MergePopulationLimit=500, ‹¯¨#=NLS_ENCODING=UTF-8, MainSearchIndex=C:/iap-data/daod1/main_index, MaxAuditSearchResults=5000, CustomIconLocation=, SearchRetrievalBatchSize=51, MaxNetworksPerNetworkSearch=5000000, LanguageCountryCode=en_US, SchemaResource=counter-fraud-schema.xml, AlertExpiryInDays=14, TopologyId=acxiom-example-id, NumberOfItemsRequestLimit=1000, LuceneMaxSortFieldLength=256, SecuritySchemaResource=example-security-schema.xml, IExternalDataSubsetLocator.modules=com.i2group.apollo.externaldata.CreatingSubsetLocatorModule, ExternalDataPersistSubsetIndexes=true, MaxNumberOfSynonymsToRetrieveForFullTextearch=100, IExternalDataAdapter.modules=, IExternalDataAdapter=, SearchService.extension.methodInterceptors=, SecurityFilterCacheMaxSize=100, AlertDispatchers.modules=com.i2group.apollo.alertretrievalservice.eventhandler.internal.PlatformAlertDispatcherModule, SchemaXsds=ModelSchema.xsd,ModelSchemaExtension.xsd,ModelSecuritySchema.xsd, IExternalDataItemEditor.modules=, AlertDispatchers=com.i2group.apollo.alertretrievalservice.eventhandler.internal.PlatformAlertDispatcher, MaximumLinksPerNetworkSearch=3, NumberScientificThreshold=15, MergeHistoryLimit=200, AuditService.extension.methodInterceptors=, IndexWriterLifetime=600000, MaximumAlternativeTermIndexWords=250000, IExternalDataItemRetriever=com.i2group.connector.acxiom.AcxiomExternalDataItemRetriever, ExternalDataSubsetDiskCacheTimeoutDays=2, DeepPagingCacheMaxAgeInMilliseconds=60000, DataSourceName=acxiom-example, AlertExpiryIntervalInSeconds=120, ExternalDataSubsetTimeoutMinutes=30, MaximumSetSizeForSearch=10000, ExternalDataSourceSearchMode=0, DuplicateItemCountLimit=10, StartupReconnectTimeoutInSeconds=120, ExternalDataSubsetsRecreatable=false, ExternalDataCreateStandardEDRSRetrievalBlock=true, PrincipalProvider=com.i2group.apollo.security.WebSphereRoleBasedPrincipalProvider, ItemRetrievalService.extension.methodInterceptors=, UserActivityLogger=com.i2group.apollo.useractivitylogger.NoOpUserActivityLogger, StartupReconnectIntervalInSeconds=20, ItemTypeFilterCacheMaxSize=100, MaxNumberOfTrigramsToRetrieveForPropertySearch=100, NetworkSearchCacheMaxAgeInMilliseconds=60000, GenerateAlternativeTermIndex=true, ChartingSchemesXsds=ModelData.xsd, MaxDumbbellResultsPerNetworkSearchSegment=10000, ItemHistoryService.extension.methodInterceptors=, IndexNonStringTypesAsStrings=true, ReconnectTimeoutInSeconds=3600, SetItemCacheThreshold=100000, SearchSummaryMaxCount=10000, IExternalDataItemEditor=com.i2group.connector.acxiom.AcxiomItemEditor, HistoricalSetCacheMaxSize=25, HighlightFragmentSize=20, UserDataSourceProvider=com.i2group.apollo.security.SimpleUserDataSourceProvider, IExternalDataItemRetriever.modules=, IExternalDataSubsetLocator=com.i2group.connector.acxiom.AcxiomDataAdapterSubset, MergeProductLimit=500, TextIndexSearcherThreadPoolSize=8, ItemDuplicateDiscriminatorLimit=1000}.
  at com.i2group.apollo.externaldata.servlet.ExternalDataServletModule.configure(ExternalDataServletModule.java:25)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.i2group.apollo.servlet.GuiceServletConfigBase.getInjector(GuiceServletConfigBase.java:49)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at com.i2group.apollo.servlet.GuiceServletConfigBase.contextInitialized(GuiceServletConfigBase.java:37)
	at com.ibm.ws.webcontainer.webapp.WebApp.notifyServletContextCreated(WebApp.java:2388)
	at [internal classes]
Caused by: java.lang.IllegalArgumentException: Parameter named 'IExternalDataDocumentSource' is not set.  Parameters were loaded from [DataSourceDaod.properties, ApolloServerSettingsCommon.properties, SearchLocalization.properties, ApolloServerSettingsCommonSearch.properties, ApolloServerSettingsSearch.properties, SearchIndexLocation.properties, ApolloServerSettingsOtherReadSide.properties, ApolloServerSettingsMandatory.properties, ApolloServerSettingsDaod.properties, ApolloServerSettingsDaodMandatory.properties], which provided {MaxNumberOfTrigramsToRetrieveForFullTextSearch=100, TransactionTimeoutInSeconds=300, ServerMaxItemVersionResultCount=1000, ReconnectIntervalInSeconds=30, DataSourceId=b962ca18-5bd5-46a5-a903-fd8d4ea94ebc, TextIndexSchedulerQueueLength=1000, ChartingSchemesResource=counter-fraud-schema-charting-schemes.xml, MaxNumberOfSynonymsToRetrieveForPropertySearch=100, ExternalDataSourceFilteredSearchMode=0, TermIndex=C:/iap-data/daod1/alternatives, MergePopulationLimit=500, ‹¯¨#=NLS_ENCODING=UTF-8, MainSearchIndex=C:/iap-data/daod1/main_index, MaxAuditSearchResults=5000, CustomIconLocation=, SearchRetrievalBatchSize=51, MaxNetworksPerNetworkSearch=5000000, LanguageCountryCode=en_US, SchemaResource=counter-fraud-schema.xml, AlertExpiryInDays=14, TopologyId=acxiom-example-id, NumberOfItemsRequestLimit=1000, LuceneMaxSortFieldLength=256, SecuritySchemaResource=example-security-schema.xml, IExternalDataSubsetLocator.modules=com.i2group.apollo.externaldata.CreatingSubsetLocatorModule, ExternalDataPersistSubsetIndexes=true, MaxNumberOfSynonymsToRetrieveForFullTextearch=100, IExternalDataAdapter.modules=, IExternalDataAdapter=, SearchService.extension.methodInterceptors=, SecurityFilterCacheMaxSize=100, AlertDispatchers.modules=com.i2group.apollo.alertretrievalservice.eventhandler.internal.PlatformAlertDispatcherModule, SchemaXsds=ModelSchema.xsd,ModelSchemaExtension.xsd,ModelSecuritySchema.xsd, IExternalDataItemEditor.modules=, AlertDispatchers=com.i2group.apollo.alertretrievalservice.eventhandler.internal.PlatformAlertDispatcher, MaximumLinksPerNetworkSearch=3, NumberScientificThreshold=15, MergeHistoryLimit=200, AuditService.extension.methodInterceptors=, IndexWriterLifetime=600000, MaximumAlternativeTermIndexWords=250000, IExternalDataItemRetriever=com.i2group.connector.acxiom.AcxiomExternalDataItemRetriever, ExternalDataSubsetDiskCacheTimeoutDays=2, DeepPagingCacheMaxAgeInMilliseconds=60000, DataSourceName=acxiom-example, AlertExpiryIntervalInSeconds=120, ExternalDataSubsetTimeoutMinutes=30, MaximumSetSizeForSearch=10000, ExternalDataSourceSearchMode=0, DuplicateItemCountLimit=10, StartupReconnectTimeoutInSeconds=120, ExternalDataSubsetsRecreatable=false, ExternalDataCreateStandardEDRSRetrievalBlock=true, PrincipalProvider=com.i2group.apollo.security.WebSphereRoleBasedPrincipalProvider, ItemRetrievalService.extension.methodInterceptors=, UserActivityLogger=com.i2group.apollo.useractivitylogger.NoOpUserActivityLogger, StartupReconnectIntervalInSeconds=20, ItemTypeFilterCacheMaxSize=100, MaxNumberOfTrigramsToRetrieveForPropertySearch=100, NetworkSearchCacheMaxAgeInMilliseconds=60000, GenerateAlternativeTermIndex=true, ChartingSchemesXsds=ModelData.xsd, MaxDumbbellResultsPerNetworkSearchSegment=10000, ItemHistoryService.extension.methodInterceptors=, IndexNonStringTypesAsStrings=true, ReconnectTimeoutInSeconds=3600, SetItemCacheThreshold=100000, SearchSummaryMaxCount=10000, IExternalDataItemEditor=com.i2group.connector.acxiom.AcxiomItemEditor, HistoricalSetCacheMaxSize=25, HighlightFragmentSize=20, UserDataSourceProvider=com.i2group.apollo.security.SimpleUserDataSourceProvider, IExternalDataItemRetriever.modules=, IExternalDataSubsetLocator=com.i2group.connector.acxiom.AcxiomDataAdapterSubset, MergeProductLimit=500, TextIndexSearcherThreadPoolSize=8, ItemDuplicateDiscriminatorLimit=1000}.
	at com.i2group.apollo.configuration.ConfigurableClassList.loadSingleClass(ConfigurableClassList.java:189)
	at com.i2group.apollo.configuration.SystemExtensionModule.<init>(SystemExtensionModule.java:82)
	at com.i2group.apollo.externaldata.servlet.ExternalDataDocumentServiceConfigurationModule$DAServletModule.<init>(ExternalDataDocumentServiceConfigurationModule.java:43)
	at com.i2group.apollo.externaldata.servlet.ExternalDataDocumentServiceConfigurationModule.configure(ExternalDataDocumentServiceConfigurationModule.java:33)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.AbstractModule.install(AbstractModule.java:118)
	at com.i2group.apollo.externaldata.servlet.ExternalDataServletModule.configure(ExternalDataServletModule.java:25)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	... 8 more

[AUDIT   ] CWWKZ0001I: Application acxiom-example started in 5.913 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [localConnector-1.0, json-1.0, appSecurity-2.0, jpa-2.0, distributedMap-1.0, jaxb-2.2, beanValidation-1.0, jdbc-4.0, ssl-1.0, jaxws-2.2, jsp-2.2, servlet-3.0, jaxrs-1.1, jndi-1.0].
[AUDIT   ] CWWKF0011I: The server acxiomread is ready to run a smarter planet.

**Comment by lawndale5** [comment]
Found and added missing property to correct ApolloServerSettingsDaodMandatory.properties file. 

# The full class name of the IExternalDataDocumentSource to use
IExternalDataDocumentSource=com.i2group.apollo.externaldata.documentstore.ExampleExternalDataDocumentSource

Launched server and logged into portal now receiving this error:
https://github.com/IBM-i2/Data-Acquisition-Accelerators/issues/6

**Comment by garywi** [comment]
Hello
You are receiving this error because you are using IAP 3.0.9 but the Acxiom connector is compatible with IAP 3.0.7 that does not have IExternalDataDocumentSource.

**Comment by stu-w** [comment]
I'm going to mark this as closed as these versions are incompatible.
